class SVGPConstants:
    NORMALIZATION = True
    CLIPPING = True

    TRAIN_INDUCING_PTS = False
    NUM_INDUCING_PTS = 1000

    BATCH_SIZE = 200
    MAX_ITER = 8000
    LEARNING_RATE = 0.005

    PRIOR_POSTERIOR_SAMPLES = 3
    PRIOR_POSTERIOR_LENGTH = 2000
