name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Static type check
        run: |
          pip install mypy
          mypy
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
      - name: Lint with pylint
        run: |
          pip install pylint
          # pylint src/ scripts/
      - name: Import sorting
        run: |
          pip install isort
          isort --check-only --diff .
      - name: Unit testing
        run: |
          pip install pytest
          pytest tests
